### ISSUE TITLE
DTO에 대한 DAO 설계 미팅 - 19.11.11 월요일 16:30~19:30 백주년

### ISSUE THREAD

**Issue by Seonmi-Hwang** [Seonmi-Hwang/DBP_recipeProject#7]
각자 DAO를 어떻게 설계할지 생각해보고
당일에 교수님께 질문드리고, 개발.

추가 질문)
1. 한 행을 삭제했을 경우 id가 연속적이지 않은 경우 (sequence를 고쳐야 하나?)
2. 추후에 개발할 문제에 대한 질문

**Comment by Carol0303** [comment]
- 이메일 체크에 관한 질문 필요!!
- DTO는 member, ingredient, recipe 세 개로 합치기
- 적어도 model.dao까지 오늘 완성
- 각 DAO는 각 DTO에 대해 만들고 ui 샘플과 usecase를 보고 필요한 동작을 구현

**Comment by Carol0303** [comment]
이메일 체크 제약조건 해결
ALTER TABLE member ADD CONSTRAINT  email_check CHECK (email_id like '%_@%_.%_');

**Comment by yejineer** [comment]
## 진행상황
### 1. 주요 내용 및 결과, 팀원별 수행 내용
- 

### 2. 문제점, 논의 사항
-


## 계획
### 3. 다음 주에 할 일
-

### 4. 기타 (역할 분담, 일정 계획 등)
-
